prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix obo: <http://purl.obolibrary.org/obo/>

select ?label where {
  { ?class rdfs:subClassOf+ obo:UBERON_0000062 ;
           rdfs:label ?label }
  UNION
  { ?class rdfs:subClassOf+ obo:UBERON_0000479 ;
           rdfs:label ?label }
}
